"""OpenAlgo execution bridge: TradeALGO decides, OpenAlgo executes.

This page is intentionally separate from the research engine. TradeALGO can generate
a deterministic strategy signal, but no order is sent unless the user explicitly
enables TRADEALGO_EXECUTION_ENABLED and confirms the order ticket.
"""

import os

import streamlit as st

from algobot import ui
from algobot.openalgo_bridge import OpenAlgoClient, OpenAlgoError

ui.setup("OpenAlgo Execution", "🔌")
ui.header(
    "OpenAlgo Execution",
    "TradeALGO owns research and signal generation. OpenAlgo owns broker authentication, routing and execution.",
    mode="execution:OpenAlgo",
)

st.info(
    "ARCHITECTURE · TradeALGO → strategy signal → OpenAlgo → broker. "
    "TradeALGO never handles broker credentials or broker-specific APIs directly."
)

try:
    client = OpenAlgoClient()
except OpenAlgoError as exc:
    st.error(str(exc))
    st.caption("Configure OPENALGO_HOST and OPENALGO_API_KEY in your private .env or Streamlit Secrets.")
    ui.check_row("FAIL", "OpenAlgo connection", "No usable OpenAlgo client is configured.")
    ui.footer_note("OpenAlgo execution is unavailable until the private connection settings are configured.")
    st.stop()

execution_enabled = client.execution_enabled()

c1, c2, c3 = st.columns(3)
c1.metric("OpenAlgo host", client.host)
c2.metric("Execution gate", "ENABLED" if execution_enabled else "LOCKED")
c3.metric("API key", "Configured")

if execution_enabled:
    st.warning(
        "⚠️ EXECUTION GATE IS ENABLED. The order button below can send an order to OpenAlgo. "
        "OpenAlgo's own configured mode determines whether the request reaches a broker or its simulator."
    )
else:
    st.success(
        "🔒 Execution is locked. Research, live charts and paper trading remain usable. "
        "Set TRADEALGO_EXECUTION_ENABLED=true only when you intentionally want order routing."
    )

if st.button("🔎 Test OpenAlgo connection", key="oa_ping", width="stretch"):
    try:
        response = client.ping()
        st.success("OpenAlgo is reachable and accepted the API key.")
        st.json(response)
    except OpenAlgoError as exc:
        st.error(str(exc))

st.divider()
st.subheader("1. Current TradeALGO signal")

snapshot = st.session_state.get("live_market_snapshot")
if snapshot:
    state = str(snapshot.get("strategy_state", "FLAT")).upper()
    suggested = {"LONG": "BUY", "SHORT": "SELL"}.get(state, "NONE")
    ui.ticker([
        ("Market", snapshot.get("market", "--"), None),
        ("Observed LTP", f"₹{float(snapshot.get('latest_price', 0)):,.2f}", None),
        ("Strategy state", state, "up" if state == "LONG" else ("down" if state == "SHORT" else None)),
        ("Suggested action", suggested, None),
    ])
    st.caption(
        "This signal was generated by TradeALGO's deterministic strategy engine from observed market data. "
        "It is not an automatic order instruction."
    )
else:
    st.info("Open Live Markets first to generate an observed strategy snapshot.")
    state = "FLAT"
    suggested = "NONE"

st.divider()
st.subheader("2. OpenAlgo order ticket")

st.caption(
    "Use the exact tradable OpenAlgo symbol. NIFTY 50 itself is an index and is not automatically assumed "
    "to be a tradable contract; for derivatives, enter the exact futures/options symbol supplied by OpenAlgo."
)

with st.form("openalgo_order"):
    left, right = st.columns(2)
    with left:
        strategy_name = st.text_input("Strategy name", value="TradeALGO Live Strategy")
        symbol = st.text_input(
            "Tradable symbol",
            value=os.environ.get("OPENALGO_SYMBOL", ""),
            placeholder="Example: NIFTY futures/options symbol from OpenAlgo",
        )
        exchange = st.text_input(
            "Exchange",
            value=os.environ.get("OPENALGO_EXCHANGE", "NFO"),
        )
        action_options = ["BUY", "SELL"]
        default_action = suggested if suggested in action_options else "BUY"
        action = st.selectbox("Action", action_options, index=action_options.index(default_action))
        quantity = st.number_input("Quantity", min_value=1, value=1, step=1)
    with right:
        pricetype = st.selectbox("Price type", ["MARKET", "LIMIT", "SL", "SL-M"])
        product = st.selectbox("Product", ["MIS", "NRML", "CNC"], index=0)
        price = st.number_input("Price", min_value=0.0, value=0.0, step=0.05)
        trigger_price = st.number_input("Trigger price", min_value=0.0, value=0.0, step=0.05)
        disclosed_quantity = st.number_input("Disclosed quantity", min_value=0, value=0, step=1)

    confirm = st.checkbox(
        "I understand this request is routed through OpenAlgo and may reach the configured broker.",
        disabled=not execution_enabled,
    )
    send = st.form_submit_button(
        "🚀 Send order through OpenAlgo",
        type="primary",
        disabled=not execution_enabled,
    )

if send:
    if not execution_enabled:
        st.error("Execution is locked.")
    elif not confirm:
        st.error("Confirm the OpenAlgo execution checkbox first.")
    elif not symbol.strip():
        st.error("Enter the exact tradable symbol.")
    elif pricetype in {"LIMIT", "SL"} and price <= 0:
        st.error("A positive price is required for LIMIT/SL orders.")
    elif pricetype in {"SL", "SL-M"} and trigger_price <= 0:
        st.error("A positive trigger price is required for SL/SL-M orders.")
    else:
        try:
            with st.spinner("Sending one order request to OpenAlgo…"):
                response = client.place_order(
                    strategy=strategy_name,
                    symbol=symbol.strip(),
                    action=action,
                    exchange=exchange.strip(),
                    pricetype=pricetype,
                    product=product,
                    quantity=int(quantity),
                    price=float(price),
                    trigger_price=float(trigger_price),
                    disclosed_quantity=int(disclosed_quantity),
                )
            order_id = response.get("orderid") or response.get("order_id")
            st.success(f"OpenAlgo accepted the order request{f' · Order ID: {order_id}' if order_id else ''}.")
            st.json(response)
            if order_id:
                st.session_state["openalgo_last_order_id"] = str(order_id)
        except OpenAlgoError as exc:
            st.error(str(exc))

st.divider()
st.subheader("3. Broker state through OpenAlgo")

if st.button("🔄 Refresh broker state", key="oa_refresh_state", width="stretch"):
    try:
        st.session_state["oa_state"] = {
            "funds": client.funds(),
            "positions": client.positions(),
            "orderbook": client.orderbook(),
        }
    except OpenAlgoError as exc:
        st.error(str(exc))

oa_state = st.session_state.get("oa_state")
if oa_state:
    tabs = st.tabs(["Funds", "Positions", "Order book"])
    with tabs[0]:
        st.json(oa_state["funds"])
    with tabs[1]:
        st.json(oa_state["positions"])
    with tabs[2]:
        st.json(oa_state["orderbook"])

last_order = st.session_state.get("openalgo_last_order_id")
if last_order:
    st.caption(f"Last TradeALGO-routed OpenAlgo order: {last_order}")
    if st.button("Check last order status", key="oa_order_status"):
        try:
            st.json(client.order_status(last_order))
        except OpenAlgoError as exc:
            st.error(str(exc))

st.divider()
ui.check_row(
    "PASS",
    "Research boundary",
    "Strategy logic and signal generation stay inside TradeALGO.",
)
ui.check_row(
    "PASS",
    "Execution boundary",
    "Broker authentication, routing and broker-specific handling stay inside OpenAlgo.",
)
ui.check_row(
    "PASS",
    "Execution gate",
    "Order methods refuse to run unless TRADEALGO_EXECUTION_ENABLED is explicitly enabled.",
)
ui.check_row(
    "PASS",
    "No order retry",
    "Order placement is never automatically retried, avoiding duplicate-order risk.",
)
ui.check_row(
    "PASS",
    "NIFTY signal vs tradable contract",
    "A NIFTY index signal does not guess an options/futures contract; the exact OpenAlgo symbol is supplied explicitly.",
)

ui.footer_note(
    "TradeALGO research + OpenAlgo execution bridge. Keep execution locked while developing strategies."
)
